---
- name: 'check if service is running'
  ansible.builtin.service:
    name: cloud-init.service
  register: service_info

- name: 'disable service'
  ansible.builtin.file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve
  become: true
  when: service_info.status.ActiveState == 'active'
