---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    device_hostname: change-hostname
    device_timezone: Europe/Amsterdam

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - role: GITHUB.UPDATE.ROLE

  tasks:
    - import_tasks: tasks/1_hostname.yml
    - import_tasks: tasks/2_timezone.yml
    - import_tasks: tasks/3_cloud_init.yml
    - import_tasks: tasks/4_zsh.yml
#    - import_tasks: tasks/5_terminator.yml
