---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    device_hostname: Raspberry-Pi-5
    device_timezone: Europe/Amsterdam

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - role: GITHUB.UPDATE.ROLE
    - role: GITHUB.HOSTNAME.ROLE
    - role: GITHUB.TIMEZONE.ROLE
