---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    <POSSIBLE VARS>

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - role: GITHUB.UPDATE.ROLE
    - role: <POSSIBLE ROLES>

  tasks:
    - import_tasks: tasks/<POSSIBLE TASKS>
